SELECT D.NAME AS DEPARTMENT,A.NAME AS EMPLOYEE,A.SALARY AS SALARY FROM (SELECT * FROM (SELECT NAME,DEPARTMENTID,SALARY,
DENSE_RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS LIM
FROM EMPLOYEE ORDER BY DEPARTMENTID ASC) E WHERE E.LIM<=3) A JOIN DEPARTMENT D ON A.DEPARTMENTID=D.ID